import type { Metadata } from "next";
import { Gentium_Plus } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar';


const gentiumPlus = Gentium_Plus({
  weight: "400",
  variable: "--font-gentium-plus",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={gentiumPlus.variable}>
          <Navbar />
          <div style={{ paddingTop: '64px' }}>
            {children}
          </div>
      </body>
    </html>
  );
}