name: run-api-ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install packages
        run: npm install

      - name: build docker image
        run: docker build -t lcdamy/qt-challenge-frontend:1.0 ./

      - name: log in to DockerHub
        run: echo ${{ secrets.DOCKER_SECRET }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: push docker image to dockerhub
        run: docker push lcdamy/qt-challenge-frontend:1.0

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: 'E4Nsc3rWU6TjtSoDQXCEWcg8'
          vercel-org-id: 'VjKHivdNGddhZVmepCek4cbG'
          vercel-project-id: 'prj_7EIacRdFh8sXlAOlNELCuU0b1EsS'
          working-directory: ./

